trigger:
- main

variables:
  DOCKER_IMAGE: "sharmila79/dummy-maven-project"
  DOCKER_CREDENTIALS_ID: "docker-id"
  SONARQUBE_SERVER: "sonar"
  SONARQUBE_TOKEN: "$(sonar)"
  KUBECONFIG_CREDENTIALS_ID: "kubernetes-id"

pool:
  name: Default
  demands:
  - agent.name -equals sqagentpool

stages:
- stage: CloneCode
  jobs:
  - job: CloneCode
    steps:
    - checkout: self
      clean: true

- stage: BuildProject
  jobs:
  - job: BuildProject
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        options: '-X'

- stage: RunUnitTests
  jobs:
  - job: RunUnitTests
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: '-X'

- stage: BuildDockerImage
  jobs:
  - job: BuildDockerImage
    steps:
    - script: docker build -t $(DOCKER_IMAGE) .

- stage: PushDockerImagetoDockerHub
  jobs:
  - job: PushDockerImagetoDockerHub
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(DOCKER_CREDENTIALS_ID)'
        repository: '$(DOCKER_IMAGE)'
        command: 'push'
        tags: 'latest'

- stage: DeploytoAKS
  jobs:
  - job: DeploytoAKS
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'my-azure-connection'  # Replace with your AzureRM service connection name
        resourceGroupName: 'your-resource-group'  # Replace with your resource group
        clusterName: 'your-aks-cluster'  # Replace with your AKS cluster name
        namespace: 'default'
        command: 'apply'
        arguments: '-f deployment.yaml'
