apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-maven-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-maven-project
  template:
    metadata:
      labels:
        app: dummy-maven-project
    spec:
      containers:
      - name: dummy-maven-project
        image: sharmila79/dummy-maven-project:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
