apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-maven-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-maven-project
  template:
    metadata:
      labels:
        app: dummy-maven-project
    spec:
      containers:
      - name: dummy-maven-project
        image: sharmila79/dummy-maven-project:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-maven-project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: dummy-maven-project
